/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTransactionsRouteImport } from './routes/app.transactions'
import { Route as AppSendRouteImport } from './routes/app.send'
import { Route as AppSecurityRouteImport } from './routes/app.security'
import { Route as AppReceiveRouteImport } from './routes/app.receive'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppMeshRouteImport } from './routes/app.mesh'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSendRoute = AppSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiveRoute = AppReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMeshRoute = AppMeshRouteImport.update({
  id: '/mesh',
  path: '/mesh',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/mesh': typeof AppMeshRoute
  '/app/profile': typeof AppProfileRoute
  '/app/receive': typeof AppReceiveRoute
  '/app/security': typeof AppSecurityRoute
  '/app/send': typeof AppSendRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/mesh': typeof AppMeshRoute
  '/app/profile': typeof AppProfileRoute
  '/app/receive': typeof AppReceiveRoute
  '/app/security': typeof AppSecurityRoute
  '/app/send': typeof AppSendRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/mesh': typeof AppMeshRoute
  '/app/profile': typeof AppProfileRoute
  '/app/receive': typeof AppReceiveRoute
  '/app/security': typeof AppSecurityRoute
  '/app/send': typeof AppSendRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/mesh'
    | '/app/profile'
    | '/app/receive'
    | '/app/security'
    | '/app/send'
    | '/app/transactions'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/mesh'
    | '/app/profile'
    | '/app/receive'
    | '/app/security'
    | '/app/send'
    | '/app/transactions'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/mesh'
    | '/app/profile'
    | '/app/receive'
    | '/app/security'
    | '/app/send'
    | '/app/transactions'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/send': {
      id: '/app/send'
      path: '/send'
      fullPath: '/app/send'
      preLoaderRoute: typeof AppSendRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/security': {
      id: '/app/security'
      path: '/security'
      fullPath: '/app/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receive': {
      id: '/app/receive'
      path: '/receive'
      fullPath: '/app/receive'
      preLoaderRoute: typeof AppReceiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mesh': {
      id: '/app/mesh'
      path: '/mesh'
      fullPath: '/app/mesh'
      preLoaderRoute: typeof AppMeshRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppMeshRoute: typeof AppMeshRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReceiveRoute: typeof AppReceiveRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSendRoute: typeof AppSendRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMeshRoute: AppMeshRoute,
  AppProfileRoute: AppProfileRoute,
  AppReceiveRoute: AppReceiveRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSendRoute: AppSendRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
